stages:
#  - build
  - publish

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  reposytory_folder: "Source/Infrastructure"
  api_folder: "Luby.TimeManager.API"

before_script:
    - ""
  

#build:
#  stage: build
#  image: mcr.microsoft.com/dotnet/sdk:5.0
#  script:
#      #- "cd Source"
#      - "dotnet restore"
#      - "dotnet build"
#  only:
#    - master

publish:
  stage: publish
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    CI_MERGE_REQUEST_SOURCE_BRANCH_NAME: test-ref-show-branch
    CI_MERGE_REQUEST_TARGET_BRANCH_NAME: master

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    #- docker run $CI_REGISTRY_IMAGE:latest

  only:
    - master